# Generated by Django 3.0.7 on 2020-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='hascs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='info',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lat',
            field=models.CharField(default='1.200', max_length=10),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lng',
            field=models.CharField(default='1.2000', max_length=10),
        ),
    ]
