# Generated by Django 3.0.7 on 2020-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200626_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='hascs',
            field=models.BooleanField(default=False, verbose_name='Has Cold Store'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lng',
            field=models.CharField(max_length=10),
        ),
    ]
