# Generated by Django 3.0.7 on 2020-06-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20200626_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='info',
        ),
    ]
