# Generated by Django 3.0.5 on 2020-05-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rprice', models.IntegerField()),
                ('wprice', models.IntegerField()),
                ('ravg', models.IntegerField()),
                ('wavh', models.IntegerField()),
            ],
        ),
    ]
