# Generated by Django 3.0.5 on 2020-05-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='ravg',
        ),
        migrations.RemoveField(
            model_name='items',
            name='wavh',
        ),
    ]
