# Generated by Django 3.0.5 on 2020-05-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200512_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='items/vege.jpg', upload_to='items'),
        ),
    ]
