# Generated by Django 3.0.5 on 2020-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
