# Generated by Django 3.0.5 on 2020-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200513_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.CharField(default='Kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='items/vege.jpg', null=True, upload_to='items'),
        ),
    ]
