# Generated by Django 3.0.5 on 2020-05-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200515_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
    ]
