# Generated by Django 3.0.5 on 2020-05-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='userlink',
            new_name='user',
        ),
    ]
