# Generated by Django 3.0.5 on 2020-05-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200509_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='ProfilePicture',
            new_name='pp',
        ),
    ]
