# Generated by Django 3.0.5 on 2020-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200509_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='pp',
            field=models.ImageField(blank=True, upload_to='pp'),
        ),
    ]
