# Generated by Django 3.0.5 on 2020-05-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_geodata_phone1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='longitude',
        ),
    ]
