# Generated by Django 3.0.5 on 2020-05-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200513_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='about',
            field=models.TextField(verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='phone1',
            field=models.CharField(max_length=13, null=True, verbose_name="Phone Number [empty if you don't want to show it]"),
        ),
    ]
