# Generated by Django 3.0.5 on 2020-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_profilepicture_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ("LET'S NOT SAY ", 'LETS NOT SAY')], default='MALE', max_length=14),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
