# Generated by Django 3.0.5 on 2020-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200522_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='phone1',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name="Phone Number [empty if you don't want to show it]"),
        ),
    ]
